const { baseDown } = require('../utils')

const table = 'user'

exports.up = async knex => {
  await knex('entity_type').insert({ table })
  await knex.schema.createTable(table, t => {
    t.bigIncrements('id').primary()
    t.uuid('uuid')
      .notNullable()
      .unique()
    t.string('user_name')
      .notNullable()
      .unique()
    t.string('display_name').notNullable()
    t.text('description')
    t.string('avatar').notNullable()
    t.string('email')
      .notNullable()
      .unique()
    t.string('mobile')
    t.text('password_hash').notNullable()
    t.integer('read_speed').defaultTo(500)
    t.integer('base_gravity')
      .notNullable()
      .defaultTo(0)
    t.integer('curr_gravity')
      .notNullable()
      .defaultTo(0)
    t.integer('mat')
      .notNullable()
      .defaultTo(0)
    t.string('language')
      .notNullable()
      .defaultTo('zh_hant')
    t.specificType('oauth_type', 'text ARRAY')
    t.enu('role', ['user', 'admin']).defaultTo('user')
    t.string('status')
      .notNullable()
      .defaultTo('enabled')
    t.timestamp('created_at').defaultTo(knex.fn.now())
    t.timestamp('updated_at').defaultTo(knex.fn.now())
  })
}

exports.down = baseDown(table)
