kind: pipeline
name: default

steps:
- name: download image
  image: plugins/ecr
  settings:
    access_key:
      from_secret: AWS_ACCESS_KEY_ID
    secret_key:
      from_secret: AWS_SECRET_ACCESS_KEY
    repo: 903380195283.dkr.ecr.ap-southeast-1.amazonaws.com/matters-server
    registry: 903380195283.dkr.ecr.ap-southeast-1.amazonaws.com
  commands:
  - echo "Hello World"  
  - aws ecr get-login --region us-east-1 | bash 
  - docker pull 903380195283.dkr.ecr.ap-southeast-1.amazonaws.com/matters-server:latest
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock

- name: install node modules
  image: matters
  commands:
  - npm install --no-progress --quiet --unsafe-perm > npm-install.log

# - name: tslint
#   image: node:8
#   commands:
#   - npm run tslint:production
#   - npm run format:check
# 
# - name: test
#   image: node:8
#   commands:
#   - npx jest
# 
# - name: deploy to stage environment
#   image: node:8
#   environment:
#     SSH_KEY:
#       from_secret: SSH_KEY
#   commands:
#   - export MATERIA_STAGE_DEPLOY_USER=ubuntu
#   - export MATERIA_STAGE_TARGET_SERVER=13.251.102.167
#   - apt-get update
#   - apt upgrade bash -y 
#   - apt install rsync -y
#   - mkdir /root/.ssh && echo "$SSH_KEY" > /root/.ssh/id_rsa && chmod 0600 /root/.ssh/id_rsa
#   - bash tools/deploy.sh build+push:stage
