kind: pipeline
name: default

steps:
- name: install node modules
  image: node:10.14
  commands:
  - npm install --no-progress --quiet --unsafe-perm >  npm-install.log

- name: tslint
  image: node:10.14
  commands:
  - npm run tslint:production
  - npm run format:check

# - name: test
#   image: node:10.14
#   commands:
#   - npx jest

- name: build
  image: node:10.14
  commands:
  - npm run build

- name: push docker image
  image: plugins/ecr
  settings:
    access_key:
      from_secret: AWS_ACCESS_KEY_ID
    secret_key:
      from_secret: AWS_SECRET_ACCESS_KEY
    region: ap-southeast-1
    repo: 903380195283.dkr.ecr.ap-southeast-1.amazonaws.com/matters-server
    registry: 903380195283.dkr.ecr.ap-southeast-1.amazonaws.com
    dockerfile: docker/Dockerfile
    tags:
    - staging
  when:
    branch:
    - develop
    - feature/beanstalk
    ref:
      exclude:
      - refs/pull/*

- name: deploy to stage environment
  image: matters/awsebcli
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION: ap-southeast-1
  commands:
  - export AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID
  - export AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY
  - export AWS_DEFAULT_REGION=AWS_DEFAULT_REGION
  - bash ./bin/eb-deploy.sh staging
  when:
    branch:
    - develop
    - feature/beanstalk
    ref:
      exclude:
      - refs/pull/*
