kind: pipeline
name: default

steps:
- name: install node modules
  image: node:8
  commands:
  - npm install --no-progress --quiet --unsafe-perm > npm-install.log

# - name: tslint
#   image: node:8
#   commands:
#   - npm run tslint:production
#   - npm run format:check
# 
# - name: test
#   image: node:8
#   commands:
#   - npx jest
# 
# - name: deploy to stage environment
#   image: node:8
#   environment:
#     SSH_KEY:
#       from_secret: SSH_KEY
#   commands:
#   - export MATERIA_STAGE_DEPLOY_USER=ubuntu
#   - export MATERIA_STAGE_TARGET_SERVER=13.251.102.167
#   - apt-get update
#   - apt upgrade bash -y 
#   - apt install rsync -y
#   - mkdir /root/.ssh && echo "$SSH_KEY" > /root/.ssh/id_rsa && chmod 0600 /root/.ssh/id_rsa
#   - bash tools/deploy.sh build+push:stage
