kind: pipeline
name: default

steps:
- name: install node modules
  image: node:10.13
  commands:
  - npm install --no-progress --quiet --unsafe-perm >  npm-install.log

- name: tslint
  image: node:10.13
  commands:
  - npm run tslint:production

# - name: test
#   image: node:10.13
#   commands:
#   - npx jest

- name: build
  image: node:10.13
  commands:
  - npm run build

- name: publish docker image
  image: plugins/docker-ecr
  settings:
    access_key:
      from_secret: AWS_ACCESS_KEY_ID
    secret_key:
      from_secret: AWS_SECRET_ACCESS_KEY
    repo: 903380195283.dkr.ecr.ap-southeast-1.amazonaws.com/matters-server
    registry: 903380195283.dkr.ecr.ap-southeast-1.amazonaws.com
    dockerfile: docker/Dockerfile

- name: deploy to stage environment
  image: matters/awsebcli
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION: ap-southeast-1
  commands:
  - eb init matters-stage --region ap-southeast-1 --source codecommit/matters-server/develop
  - eb codesource local
  - eb deploy matters-server-stage
  when:
    branch:
    - develop
    - feature/beanstalk
