AWSTemplateFormatVersion: 2010-09-09

Description: Queue Job Lambda

Parameters:
  imageUri:
    Type: String
    Description: "The Amazon ECR image URI"
  mattersEnv:
    Type: String
    Description: 'Lambda environment, which will determine the ssm parameter path to query'
  lambdaCMD:
    Type: String
    Description: 'lambda CMD setting'
  lambdaTimeout:
    Type: Number
    Description: 'lambda timeout setting'
  lambdaMemorySize:
    Type: Number
    Description: 'lambda memory size setting'
  lambdaReservedConcurrency:
    Type: Number
    Description: 'The reserved concurrency limit for the Lambda function'
    Default: 10
  sqsArn:
    Type: String
    Description: 'The ARN of the SQS queue to use as trigger'
  sqsBatchSize:
    Type: Number
    Description: 'The batch size of the SQS queue to use as trigger'
  sqsMaxBatchingWindowInSeconds:
    Type: Number
    Description: 'The maximum batching window in seconds of the SQS queue to use as trigger'

Conditions:
  isProd: !Equals
    - !Ref mattersEnv
    - "production"

Resources:
  Lambda:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        ImageUri: !Ref imageUri
      PackageType: Image
      ImageConfig:
        Command:
          - !Ref lambdaCMD
      Environment:
        Variables:
          MATTERS_ENV: !Ref mattersEnv
      Architectures:
        - x86_64
      MemorySize: !Ref lambdaMemorySize
      Timeout: !Ref lambdaTimeout
      ReservedConcurrentExecutions: !If
        - isProd
        - !Ref lambdaReservedConcurrency
        - 1
      Role: !GetAtt LambdaRole.Arn
      VpcConfig:
        SecurityGroupIds:
          - !If
            - isProd
            - sg-0a1928a3b07644413
            - sg-08ca5c76639a365d3
        SubnetIds:
          - !If
            - isProd
            - subnet-0415147ddf68a48f2
            - subnet-0c6a762428d442ec3

  LambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole

  LambdaRolePolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      Roles:
        - !Ref LambdaRole
      PolicyName: "cronjobLambda"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - "ssm:GetParameter"
              - "ssm:GetParametersByPath"
            Effect: Allow
            Resource: !Join
              - ""
              - - "arn:"
                - !Ref "AWS::Partition"
                - ":ssm:"
                - !Ref "AWS::Region"
                - ":"
                - !Ref "AWS::AccountId"
                - !If
                  - isProd
                  - ":parameter/prod/matters-server/"
                  - ":parameter/dev/matters-server/"
          - Action:
              - "sqs:ReceiveMessage"
              - "sqs:DeleteMessage"
              - "sqs:GetQueueAttributes"
            Effect: Allow
            Resource: !Ref sqsArn

  SQSEventSourceMapping:
    Type: "AWS::Lambda::EventSourceMapping"
    Properties:
      EventSourceArn: !Ref sqsArn
      FunctionName: !Ref Lambda
      BatchSize: !Ref sqsBatchSize
      MaximumBatchingWindowInSeconds: !Ref sqsMaxBatchingWindowInSeconds
      FunctionResponseTypes:
        - ReportBatchItemFailures