CREATE SCHEMA IF NOT EXISTS :schemaname ;
COMMENT ON SCHEMA :schemaname IS :comment ;

GRANT SELECT ON ALL TABLES IN SCHEMA :schemaname TO PUBLIC ;

ALTER DEFAULT PRIVILEGES IN SCHEMA :schemaname GRANT SELECT ON TABLES TO PUBLIC ;

GRANT USAGE ON SCHEMA :schemaname TO PUBLIC;

CREATE TABLE :schemaname.u1 AS SELECT 1 AS c1;
