name: Test

on:
  push:
    branches-ignore:
      - develop
      - main
      - master
      - stage

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      elasticsearch:
        image: elasticsearch:8.2.3
        ports:
          - 9200:9200
        env:
          discovery.type: single-node
          xpack.security.enabled: false
      ipfs:
        image: ipfs/go-ipfs:v0.14.0
        ports:
          - 5001:5001
      stripe:
        image: stripemock/stripe-mock:latest
        ports:
          - 12111:12111
          - 12112:12112

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Start VPN
        run: |
          sudo apt-get update \
          && sudo apt-get install openvpn \
          && echo $VPN_CONFIG | base64 -d >> $VPN_CONFIG_PATH \
          && echo $VPN_AUTH | base64 -d >> $VPN_AUTH_PATH \
          && sudo openvpn --config $VPN_CONFIG_PATH --auth-user-pass $VPN_AUTH_PATH --daemon \
          && sleep 15s
        env:
          VPN_CONFIG: ${{ secrets.VPN_CONFIG }}
          VPN_CONFIG_PATH: '.github/config.ovpn'
          VPN_AUTH: ${{ secrets.VPN_AUTH }}
          VPN_AUTH_PATH: '.github/auth.txt'

      - name: Check DB Connection
        run: nc -zv -w 5 $MATTERS_PG_HOST 5432
        env:
          MATTERS_PG_HOST: ${{ secrets.PROD_PG_HOST }}

      - name: Kill VPN
        if: always()
        run: sudo killall openvpn || true
